import type { Metadata } from "next";

import "./globals.css";

import { Suspense } from "react";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav style={{ display: 'flex', flexDirection: 'column' }}>
          <Link href="/A">A</Link>
          <Link href="/B">B</Link>
        </nav>
        <Suspense>
          <main>
            {children}
          </main>
        </Suspense>
      </body>
    </html>
  );
}
